apiVersion: v1
kind: Pod
metadata:
  name: loss-landscape-dev-pod
spec:
  containers:
  - name: gpu-container
    image: jupyter/scipy-notebook
    command: ["jupyter", "lab", "--NotebookApp.token=627a7b3b"]
    volumeMounts:
    - mountPath: /loss_landscape
      name: loss-landscape-volume
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "32G"
        cpu: "8"
  restartPolicy: Never
  volumes:
    - name: loss-landscape-volume
      persistentVolumeClaim:
        claimName: loss-landscape-volume