apiVersion: v1
kind: Pod
metadata:
  name: dev-ll-pod
spec:
  containers:
  - name: gpu-container
    image: jupyter/scipy-notebook
    command: ["/bin/bash","-c"]
    args: ["git clone https://github.com/balditommaso/loss_landscape_taxonomy.git;
            cd loss_landscape_taxonomy;
            conda env create -f environment.yml;
            source activate loss_landscape;
            . scripts/get_econ_data.sh;
            cd /;
            jupyter lab --NotebookApp.token=627a7b3b;"]
    volumeMounts:
    - mountPath: /loss_landscape
      name: loss-landscape-volume
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "128G"
        cpu: "16"
  restartPolicy: Never
  volumes:
    - name: loss-landscape-volume
      persistentVolumeClaim:
        claimName: loss-landscape-volume