apiVersion: batch/v1
kind: Job
metadata:
    name: jtag-bs1024-lr0-1
spec:
    template:
        spec:
            restartPolicy: Never
            containers:
              - name: gpu-container
                image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/scipy
                command: ["/bin/bash","-c"]
                args: ["git clone https://github.com/balditommaso/loss_landscape_taxonomy.git;
                        cd /home/jovyan/loss_landscape_taxonomy;
                        conda env create -f environment.yml;
                        . /home/jovyan/loss_landscape_taxonomy/workspace/models/econ/scripts/jet_dataset_download.sh;
                        source activate loss_landscape;
                        cd /home/jovyan/loss_landscape_taxonomy/workspace/models/jets/;
                        . scripts/train.sh                                         --bs 1024                                         --lr 0.1                                         --max_epochs 25                                         --top_models 3                                         --num_test 3                                         --num_workers 8                                         --accelerator auto;"]
                volumeMounts:
                  - mountPath: /loss_landscape
                    name: loss-landscape-volume
                resources:
                    limits:
                        nvidia.com/gpu: "1"
                        memory: "128G"
                        cpu: "32"
                    requests:
                        nvidia.com/gpu: "1"
                        memory: "128G"
                        cpu: "32"
            restartPolicy: Never
            volumes:
                  - name: loss-landscape-volume
                    persistentVolumeClaim:
                        claimName: loss-landscape-volume
