apiVersion: batch/v1
kind: Job
metadata:
    name: test
spec:
    template:
        spec:
            restartPolicy: Never
            containers:
              - name: gpu-container
                image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/scipy
                command: ["/bin/bash","-c"]
                args: ["git clone https://github.com/balditommaso/loss_landscape_taxonomy.git;
                        cd /home/jovyan/loss_landscape_taxonomy;
                        conda env create -f environment.yml;
                        . scripts/get_econ_data.sh;
                        source activate loss_landscape;
                        cd /home/jovyan/loss_landscape_taxonomy/workspace/models/econ/;
                        . scripts/train.sh                                         --bs 2000                                         --lr 0.1                                        --max_epochs 1                                     --size small                                         --top_models 1                                    --num_test 3                                         --num_workers 8                                         --accelerator auto;
                        tar -czvf /loss_landscape/test.tar.gz /home/jovyan/checkpoint/different_knobs_subset_10 ;"]
                volumeMounts:
                  - mountPath: /loss_landscape
                    name: loss-landscape-volume
                resources:
                    limits:
                        nvidia.com/gpu: "1"
                        memory: "128G"
                        cpu: "32"
                    requests:
                        nvidia.com/gpu: "1"
                        memory: "128G"
                        cpu: "32"
            volumes:
                  - name: loss-landscape-volume
                    persistentVolumeClaim:
                        claimName: loss-landscape-volume
