apiVersion: batch/v1
kind: Job
metadata:
  name: train-bs-job
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: jupyter/scipy-notebook
        command: ["/bin/bash","-c"]
        args: ["git clone https://github.com/balditommaso/loss_landscape_taxonomy.git;
                cd $HOME/loss_landscape_taxonomy;
                conda env create -f environment.yml;
                . scripts/get_econ_data.sh;
                source activate loss_landscape;
                . $HOME/loss_landscape_taxonomy/workspace/models/econ/scripts/train.sh --process_data --scan bs;
                mv $HOME/loss_landscape_taxonomy/workspace/checkpoint /loss_landscape;"]
        volumeMounts:
        - mountPath: /loss_landscape
          name: loss-landscape-volume
        resources:
          limits:
            nvidia.com/gpu: "8"
            memory: "64G"
            cpu: "16"
          requests:
            nvidia.com/gpu: "8"
            memory: "64G"
            cpu: "16"
      restartPolicy: Never
      volumes:
        - name: loss-landscape-volume
          persistentVolumeClaim:
            claimName: loss-landscape-volume