apiVersion: v1
kind: Pod
metadata:
  name: loss-landscape-training-pod
spec:
  containers:
  - name: gpu-container
    image: condaforge/mambaforge
    command: ["echo", "Start job"]
    args: ["mkdir checkpoint; cd checkpoint;
            touch test.txt; echo 123 > test.txt;"]
    volumeMounts:
    - mountPath: /checkpoint
      name: loss-landscape-volume
    resources:
      limits:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "8"
  restartPolicy: Never
  volumes:
    - name: loss-landscape-volume
      persistentVolumeClaim:
        claimName: loss-landscape-volume