apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loss-landscape-volume
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti